apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: semics
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: appV9
  name: appV9
  namespace: semics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appV9
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: appV9
    spec:
      containers:
      - image: acrsharedcommon55709.azurecr.io/appV9
        name: appV9
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: appV9
  name: appV9
  namespace: semics
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: appV9
  type: ClusterIP
status:
  loadBalancer: {}
